#ifndef TP_CPP3_ERRORCODE_H
#define TP_CPP3_ERRORCODE_H

const int UNKNOWN_COMMAND = 10;

const int INVALID_PARAMETERS = 100;
const int NAME_ALREADY_USED = 101;
const int NAME_NOT_USED = 102;

const int POLYGON_IS_NOT_CONVEX = 110;
const int POLYGON_LESS_THAN_3 = 111;

const int UNKNOWN_FILE_ERROR = 120;
const int FILE_DOES_NOT_EXIST = 121;

#endif //TP_CPP3_ERRORCODE_H
